apiVersion: apps/v1 
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: master
        image: gcr.io/datacenter-293401/worker-app:v1
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
        ports:
        - containerPort: 5230
---
