FROM ubuntu:18.04
RUN apt-get update
RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y python3.6
RUN apt-get install -y python3-pip
RUN pip3 install pika
RUN mkdir /rest
RUN chmod -R 777 /rest
WORKDIR /rest
COPY . /rest
CMD  python3 logs.py